#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/bootstrap.php';

use Dachande\Weecast\Application\Application;

$application = new Application();
$application->run();
